diyan/pywinrm

winrm/protocol.py, winrm/transport.py
allows server certificate validation to be ignored for SSLContext-aware Python (>= 2.7.9)
server_cert_validation arg is a string for a couple of reasons:
- allows for more granular behavior later (ignore_hostname, ignore_expired, etc)
- (selfish reason) Ansible connection plugin can only pass through kwargs as strings
=> added server_cert_validation arg

winrm/transport.py
WinRMTransportError was called with only one argument instead of two, raising the type error:
TypeError: __init__() takes exactly 3 arguments (2 given)
=> Fixed bug in transport.py

setup.cfg
In order to build rpm for this library, it requires adding dependency to build proper rpm package.
=> Adding setup.cfg to configure command for rpm build

winrm/transport.py
Had to make some tweaks to client cert auth to get it working again with the SSLContext stuff (hadn't tested that part of the previous PR).
=> fixed client cert auth with SSLContext

winrm/__init__.py
hi.
I've noticed I cannot access initialization of self.protocol in Session(), if I want to pass various ssl related params (certificates), so to be able to do this - I'm adding **kwargs.
I could have explicitly specified what protocol params I want to pass, but this would be of lower future compatiblity.
This seems to break nothing and seems to not require any additional tests.
Tell me what you think.
=> update __init__ for Session to get argbitrary keywords for use with ssl

winrm/transport.py
On some platforms (RHEL7 using ansible) the warnings are not being suppressed.
Looking into this, the try-except block failed with the error `cannot import name InsecurePlatformWarning`.
So it is safer to import and filter each warning individually.
This fixes ansible/ansible#20006
=> Ensure suppressing urllib3 warning works correctly

CHANGELOG.md, README.md, appveyor.yml, setup.cfg, winrm/encryption.py, winrm/protocol.py, winrm/tests/test_encryption.py, winrm/transport.py
Added support for message encryption with NTLM authentication detailed here https://github.com/diyan/pywinrm/issues/127.
Also fixed up some minor changes in the README that were incorrect.
@nitzmahone no rush with this but happy to see your thoughts on this and if there are better ways of doing this compared to the change.
=> NTLM/CredSSP Message Encryption

winrm/transport.py
The python requests module uses .verify i) as boolean or ii) path to a custom CA bundle, see http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification
This change makes use of the already present ca_trust_path and passes it properly to the requests library, enabling custom CAs in addition to the built-in mozilla chain.
=> pass ca_trust_path to requests module

winrm/exceptions.py, winrm/protocol.py, winrm/transport.py
If it is an application-level fault and the endpoint returns a vaild SOAP envelope, the current implementation throws off the entire message and simply reports it as a transport failure, which is not helpful.
This patch modifies `winrm.protocol.Protocol.send_message` so 
1. it raises WinRMError instead of WinRMTransportError when the fault isn't of transport.
2. the raised exception contains the fault code, subcode and reason text from the payload when applicable.
=> Emit as detailed error messages as possible when the fault isn't of transport.

.travis.yml, appveyor.yml, requirements-test.txt, winrm/protocol.py, winrm/tests/test_protocol.py, winrm/transport.py
Attempt to parse the *_timeout_sec variables and fail with a better error message
Will fix the following issues in Ansible without us manually handling it there.
https://github.com/ansible/ansible/issues/33339
https://github.com/ansible/ansible/issues/25539
Also set's a limit on the pytest version to `3.2.5` as `3.3.0` drops support for Python 2.6 and 3.3.
=> Int parser for timeout and kerb arg support

winrm/transport.py
I had the problem on a RHEL7 server that the old fix did not work for the insecure request warnings.
The proposed change did the job and warnings were not shown anymore.
It seems that requests.packages.urllib3.exceptions does not equal to urllib3.exceptions when using warnings.simplefilter.
=> additional filter to supress urllib3 warnings

winrm/tests/test_transport.py, winrm/transport.py
If ca_trust_path is passed into winrm.Protocol, it is generally ignored. This change uses it as well as the possible request environment variables (REQUESTS_CA_BUNDLE and CURL_CA_BUNDLE) to trust a local CA.
=> Allow internal Certificate Authority

winrm/tests/test_transport.py, winrm/transport.py
* fixes #201
* ensures that `server_cert_validation` takes precedence over code/env CA path overrides
* adds basic unit test coverage of verify behavior
=> fix env cert validation override

.travis.yml, CHANGELOG.md, appveyor.yml, setup.py, winrm/encryption.py, winrm/tests/test_encryption.py, winrm/transport.py
Set the minimum version of the requests-credssp client to 1.0.0 due to recent changes in that library. Due to a bug where each session was created per session instead of per host I've had to deprecate the old interface and create a new one that is similar to the requests-kerberos interface. This PR also brings in some more configuration options around CredSSP auth that were introduced by Microsoft in a recent security patch.
These changes are reliant on https://github.com/jborean93/requests-credssp/pull/7 being merged and released to Pypi.
=> Added CredSSP changes to support kerb auth and newer protocol changes

winrm/__init__.py, winrm/tests/test_session.py
The output from WinRM is a byte string and on Python 3 the Session class tries to clear up the clixml that is produced on the stderr. Currently it expects a text/unicode string which is fine on Python 2 but doesn't work on 3. This PR fixes that issue and ensure the stderr is cleaned and outputted properly as per before.
Supersedes:
* https://github.com/diyan/pywinrm/pull/112
* https://github.com/diyan/pywinrm/pull/137
* https://github.com/diyan/pywinrm/pull/178
* https://github.com/diyan/pywinrm/pull/218
* https://github.com/diyan/pywinrm/pull/220
=> Fix for session clixml encoding on Python 3

winrm/protocol.py, winrm/tests/test_integration_protocol.py
Closes #255 
Properly sets all environment variables by adding them to a list.
=> #255 - Fix for shell not setting all environment variables

.gitignore, CHANGELOG.md, winrm/__init__.py, winrm/protocol.py, winrm/tests/test_transport.py, winrm/transport.py
Merging #196 with the latest from master.
This patch adds support for setting the proxy via a string. It also adds support for ignoring any environment variables that may set proxies.
This patch supersedes PR #165 and PR #151, but should implement what was requested in PR #165.
Example HTTP proxy strings are http://server:port and http://user:pass@server:port. An example SOCKS5 proxy string is socks5://user:pass@server:port.
=> mcassaniti's proxy support

CHANGELOG.md, MANIFEST.in, winrm/protocol.py, winrm/tests/test_transport.py, winrm/transport.py
This patch adds support for setting the proxy via a string. It also adds support for ignoring any environment variables that may set proxies.
This patch supersedes PR #165 and PR #151, but should implement what was requested in PR #165.
Example HTTP proxy strings are http://_server_:_port_ and http://_user_:_pass_@_server_:_port_. An example SOCKS5 proxy string is socks5://_user_:_pass_@_server_:_port_.
=> Support setting a proxy and ignoring proxies from environment

winrm/tests/conftest.py, winrm/tests/test_session.py, winrm/tests/test_transport.py
This PR relates to #197.
I've added the following tests for Transport.build_session:
- Testing that a trusted CA path sets session.verify regardless of server_cert_validation
- Tested server_cert_validation=ignore code path
- Tested invalid server_cert_validation value
- Tested Kerberos delegation value as both valid and invalid string
- Tested not providing a username or password when they should be required
- Tested setting an invalid authentication mechanism
- Tested setting an invalid encryption setting
I've also added a Session.run_ps test which should test various code paths. The test returns an error, so the std_err and return code are also tested.
=> Added several tests based off missing code coverage

CHANGELOG.md
Updating the CHANGELOG with a couple other PRs that have been merged that directly impacts pywinrm.
Changing the version to 0.4.0 since there have been new features added so far, primarily the proxy functionality.
=> Updating CHANGELOG for based on PR merges so far.

CHANGELOG.md, winrm/protocol.py, winrm/tests/test_transport.py, winrm/transport.py
The following is to provide `DeprecationWarning` for CA trusts defined by Environment Variables, if found.
The goal is to eventually require the CA trusts to be provided explicitly.
=> Add deprecated warnings for CA Trusts defined by Env Var

CHANGELOG.md, winrm/protocol.py, winrm/tests/conftest.py, winrm/tests/test_protocol.py, winrm/tests/test_transport.py, winrm/transport.py
This will allow for completely disconnecting from the server if the shell has closed, closing all TCP connections. The existing behavior should be the same. 
There was some unit tests added to mock requests in PR https://github.com/diyan/pywinrm/pull/131 . If you would like additional unit tests, I can either wait for that PR to be merged or move both code into one to re-use what is there.
=> Allow for disconnect from server on shell close.

.coveragerc, setup.py, winrm/transport.py, winrm/vendor/requests_kerberos/__init__.py, winrm/vendor/requests_kerberos/compat.py, winrm/vendor/requests_kerberos/exceptions.py, winrm/vendor/requests_kerberos/kerberos_.py
Pending upstream changes will cause significant breakage; just embed a working one. See https://github.com/requests/requests-kerberos/pull/133 and https://github.com/requests/requests-kerberos/pull/114 for more details.
Fixes #267
=> vendor requests_kerberos v0.12.0

winrm/protocol.py, winrm/tests/conftest.py, winrm/tests/test_protocol.py
This should put to rest [Issue 72](https://github.com/diyan/pywinrm/issues/72).  This expands the capabilities of pywinrm to be able to send input to an already running process.
=> Add a function to send input to a running process.

CHANGELOG.md, winrm/transport.py
Removed dependency on `distutils` which is deprecated in Python 3.10 and is slated to be removed in 3.12.
=> Remove distutils dependency

.github/workflows/ci.yml, CHANGELOG.md, requirements-test.txt, setup.py, winrm/transport.py
`inspect.getargspec` was deprecated and is now removed in python 3.11. This removes the usage of this function and bumps the minimum version for `requests-ntlm` to ensure the arguments specified are valid. The version of `requests-ntlm` has been out for 5 years so so it should be safe to set as a minimum.
=> Remove inspect method for Python 3.11

.github/workflows/ci.yml, .gitignore, pyproject.toml, requirements-test.txt, winrm/__init__.py, winrm/encryption.py, winrm/exceptions.py, winrm/protocol.py, winrm/transport.py
Add type annotations to the pywinrm library. This can help reduce type
related bugs inside the library and also help callers to figure out the
correct values that can be used in the public API.
=> Add type annotations

CHANGELOG.md, winrm/exceptions.py, winrm/protocol.py, winrm/tests/test_exceptions.py
Adds the new exception WSManFaultError which inherits from WinRMError and will be raised when receiving a WSManFault from the server. This new exception type contains detailed information that could be relevant to the caller when trying to handle the specific exception.
=> Add WSManFaultError

CHANGELOG.md, winrm/protocol.py, winrm/tests/test_protocol.py
Adds new APIs on the protocol class to expose a publicly supported way to build the WSMan SOAP headers used internally and to get a single output value. The original methods have been kept around for backwards compatibility as while they were not set as public they have been used in various libraries so removing them now will cause breakages.
=> Add new public APIs for header and command output

requirements-test.txt, winrm/tests/conftest.py, winrm/tests/test_transport.py
Hi,
As only Py3.8+ is supported, usage of old external mock does not makes sense anymore (It is stuck forever at the snapshot of stdlib from Py3.6)  #345 
Greetings
---
https://github.com/testing-cabal/mock
mock is now part of the Python standard library, available as [unittest.mock](https://docs.python.org/dev/library/unittest.mock.html) in Python 3.3 onwards.
=> drop dependency on old external mock module
